### ISSUE TITLE
Fatal Javascript Error when clicking on Notification

### ISSUE THREAD

**Issue by mountainash** [uffou/MixCloud-Play#6]
```
A JavaScript error occurred in the main process

Uncaught Exception:
ReferenceError: notificationIndex is not defined
    at Notification.notification.on (/Users/rowanw/Sites/test/github/MixCloud-Play/dist/mac/MixCloud Play.app/Contents/Resources/app.asar/build/main.js:197:60)
    at emitOne (events.js:116:13)
    at Notification.emit (events.js:211:7)
```
When click on the macOS notification (alert) a dialogue with the above error shows - often the app will then exit (not always).

/assign @mountainash
/label ~Doing

**Comment by mountainash** [comment]
I've fixed this in my Fork and will raise a MR soon.

**Comment by mountainash** [comment]
> I've fixed this in my Fork and will raise a MR soon.

Done in #8 - ready for the Maintainer to review/release.
